
name: Nix flake check on commit

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  nix-flake-check:
    runs-on: nix-native
    env:
      PATH: /home/gitea-runner/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/usr/local/bin:/usr/bin:/bin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Attic and use it
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_TOKEN }}
        run: |
          attic login attic-awroo-fun https://attic.awroo.fun $ATTIC_TOKEN

      - name: Set up SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          cat <<EOF > ~/.ssh/id_gitea
          $SSH_PRIVATE_KEY
          EOF

          cat <<EOF > ~/.ssh/known_hosts
          $KNOWN_HOSTS
          EOF
          
          chmod 600 ~/.ssh/id_gitea
          echo -e "Host gt.awroo.fun\n IdentityFile ~/.ssh/id_gitea\n IdentitiesOnly yes\n Port 2220\n HostName 89.176.245.38" > ~/.ssh/config
          ssh -T git@gt.awroo.fun

      - name: Check the flake
        run: |
          nix flake check
